background       = "background"
background-alpha = 1.0
text             = "foreground"
placeholder      = "muted"
text-error       = "urgent"
border           = "hyprland.active-border"
border-active    = "hyprland.active-border"
border-error     = "urgent"
border-alpha     = 1.0
selection        = "foreground"
selection-alpha  = 0.45
