background                = "background"
background-alpha          = 1.0
text                      = "foreground"
border                    = "hyprland.active-border-foreground"
border-alpha              = 1.0
scrim                     = "background"
scrim-alpha               = 0.75
selected-background       = "foreground"
selected-background-alpha = 0.12
selected-text             = "#C8FFC8"
selected-border           = "hyprland.active-border-foreground"
selected-border-alpha     = 0.25
